version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - fullcycle_network

  app:
    build: ./app
    container_name: node_app
    volumes:
      - ./app:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=fullcycle
    depends_on:
      - db
    networks:
      - fullcycle_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullcycle_network

networks:
  fullcycle_network:
    driver: bridge

volumes:
  mysql_data:
